---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfgarden/garden-ci
    tag: '2.0.11'

inputs:
- name: gr-release-develop

caches:
- path: gr-release-develop/bin
- path: gr-release-develop/pkg

run:
  dir: gr-release-develop/src/grootfs
  path: make
  user: root

