---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: cfgarden/garden-ci
    tag: '2.0.17'

inputs:
- name: gr-release-develop

caches:
- path: gr-release-develop/bin
- path: gr-release-develop/pkg

params:
  DOCKER_REGISTRY_USERNAME:
  DOCKER_REGISTRY_PASSWORD:
  GROOTFS_USER: whoever

run:
  dir: gr-release-develop/src/grootfs
  path: ci/scripts/unit-tests.sh
  user: root
