---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfgarden/garden-ci
    tag: '2.0.14'

inputs:
- name: gr-release-develop

caches:
- path: gr-release-develop/bin
- path: gr-release-develop/pkg

params:
  DOCKER_REGISTRY_USERNAME:
  DOCKER_REGISTRY_PASSWORD:
  GROOTFS_TEST_UID: 0
  GROOTFS_TEST_GID: 0
  GROOTFS_USER: whoever

run:
  dir: gr-release-develop/src/grootfs
  path: ci/scripts/integration-tests.sh
  user: root
