- type: replace
  path: /instance_groups/0/jobs/name=garden/properties/garden/experimental_rootless_mode?
  value: true

- type: replace
  path: /instance_groups/0/jobs/name=garden/properties/grootfs?/skip_mount?
  value: true
