- type: replace
  path: /instance_groups/0/jobs/name=garden/properties/garden/experimental_rootless_mode?
  value: true

- type: replace
  path: /instance_groups/0/jobs/name=garden/properties/garden/network_plugin?
  value: /bin/true

- type: replace
  path: /instance_groups/0/jobs/name=grootfs/properties/grootfs/driver?
  value: btrfs

- type: remove
  path: /instance_groups/0/jobs/name=garden/properties/garden/privileged_image_plugin?

- type: remove
  path: /instance_groups/0/jobs/name=garden/properties/garden/privileged_image_plugin_extra_args?
