autoconf/autoconf-2.72.tar.gz:
  size: 2143794
  object_id: de05bbf1-1ab7-4c21-4add-859e81b80b84
  sha: sha256:afb181a76e1ee72832f6581c0eddf8df032b83e2e0239ef79ebedc4467d92d6e
automake/automake-1.17.tar.gz:
  size: 2451070
  object_id: 53b1a04f-256f-4eea-6c54-ad1cac93c6b3
  sha: sha256:397767d4db3018dd4440825b60c64258b636eaf6bf99ac8b0897f06c89310acd
busybox/busybox-1.36.1.tar.gz:
  size: 2524386
  object_id: dcbd055b-aa50-4729-522a-55f30dd57aef
  sha: sha256:68175336cdd42fecc2cd00851e9555fb2aebfe9f50d91ce8f9fb6708dba77110
gperf/gperf-3.1.tar.gz:
  size: 1215925
  object_id: 756c90ec-175f-4b1a-482d-de2461421ea5
  sha: sha256:588546b945bba4b70b6a3a616e80b4ab466e3f33024a352fc2198112cdbb3ae2
iptables/iptables-1.8.10.tar.xz:
  size: 641168
  object_id: fd8cb91a-ef7c-4150-7b32-0aa43b982d83
  sha: sha256:5cc255c189356e317d070755ce9371eb63a1b783c34498fb8c30264f3cc59c9c
iptables/libmnl-1.0.5.tar.bz2:
  size: 314791
  object_id: 38e97674-46be-432a-46e8-d4b9278ffb19
  sha: sha256:274b9b919ef3152bfb3da3a13c950dd60d6e2bcd54230ffeca298d03b40d0525
iptables/libnftnl-1.2.7.tar.xz:
  size: 343876
  object_id: 20407fb6-e9ce-47bb-70b4-e0170435eeba
  sha: sha256:9122774f968093d5c0bacddd67de480f31fa4073405a7fc058a34b0f387aecb3
libseccomp/libseccomp-2.5.5.tar.gz:
  size: 642445
  object_id: 1e0357af-031f-42d0-68c2-e77256b3728c
  sha: sha256:248a2c8a4d9b9858aa6baf52712c34afefcf9c9e94b76dce02c1c9aa25fb3375
libtool/libtool-2.4.6-14.tar.gz:
  size: 1881027
  object_id: ed6d266e-0b65-4693-59d7-cf6b5d3b6c5b
  sha: sha256:a74985cfb8a5fe30a0b6e0655c31432b299df1cf1734dd64baa0f99be8ee7d27
lzo/lzo-2.09.tar.gz:
  size: 594855
  object_id: 39bb6d9a-e168-4137-7751-c8262b743f1d
  sha: e2a60aca818836181e7e6f8c4f2c323aca6ac057
musl/musl-1.2.5.tar.gz:
  size: 1080786
  object_id: 0721c194-e206-4fb7-7564-a5333458a927
  sha: sha256:a9a118bbe84d8764da0ea0d28b3ab3fae8477fc7e4085d90102b8596fc7c75e4
pkg-config/pkg-config-0.29.2.tar.gz:
  size: 2016830
  object_id: 047ac8ff-aae8-4df3-6746-3f05cfdbfc3b
  sha: sha256:6fc69c01688c9458a57eb9a1664c9aba372ccda420a02bf4429fe610e7e7d591
tar/tar-1.35.tar.xz:
  size: 2317208
  object_id: 0091a979-2720-4f67-75e6-f617f395a6ec
  sha: sha256:4d62ff37342ec7aed748535323930c7cf94acf71c3591882b26a7ea50f3edc16
tini/tini-0.19.0.tar.gz:
  size: 32369
  object_id: e542dbad-4e45-40fc-43fd-49f7561ab600
  sha: sha256:0fd35a7030052acd9f58948d1d900fe1e432ee37103c5561554408bdac6bbf0d
util-linux/util-linux-2.39.4.tar.gz:
  size: 18915279
  object_id: 1bae6ff3-67e5-4d5e-7ecb-63706ebda274
  sha: sha256:b1ce77f20e080449d44b40b2f9570cc230584b7ae6439277473679888ac2bfe6
xfs-progs/xfsprogs-4.20.0.tar.gz:
  size: 1750213
  object_id: 46a0233d-1423-46d8-49ad-b5d0f07a39aa
  sha: 46c23a0e222a3374d9c739b8c44be879712e6e75
zlib/zlib-1.3.1.tar.gz:
  size: 1512791
  object_id: b8fa21de-44d4-4577-635d-04152304a333
  sha: sha256:9a93b2b7dfdac77ceba5a558a580e74667dd6fede4585b91eefb60f03b72df23
