---
iptables/iptables-1.4.21.tar.bz2:
  object_id: 66b91b2f-bbd2-42f7-af53-286e7cefa63a
  sha: 85d4160537546a23a7e42bc26dd7ee62a0ede4c8
  size: 547439
shadow/shadow-4.2.1.tar.gz:
  object_id: aea45a48-df25-424e-9ddb-bbcc89ab3cbb
  sha: 1d205418863dd02b2b8af0fa78fcce5d7c848d1f
  size: 3686676
busybox/busybox.tar.gz:
  object_id: cc631520-0a72-4cb1-8c87-700f6bdd3305
  sha: 6410617b26644ab3fac9372494cabe34e269970c
  size: 1145751
tar/tar-1.28.tar.gz:
  object_id: 5b4d9521-12c3-434f-b537-2df64f0b5764
  sha: cd30a13bbfefb54b17e039be7c43d2592dd3d5d0
  size: 3877043
golang/go1.6.1.linux-amd64.tar.gz:
  object_id: 9e9bda5c-03df-4dba-ab5d-a938cf289edb
  sha: c73492474dcc7a233772d27e948b74468d9f1849
  size: 84824395
