apparmor/apparmor-2.13.2.tar.gz:
  size: 7369240
  object_id: 3baa1660-b997-47b5-4fad-336937db42b0
  sha: e3ba457792f42178be5cd18192dc1af53e336503
autoconf/autoconf-2.69.tar.gz:
  size: 1927468
  object_id: c2a13621-9ec0-4da4-7ce7-229066284651
  sha: 562471cbcb0dd0fa42a76665acf0dbb68479b78a
automake/automake-1.15.tar.gz:
  size: 2244206
  object_id: a7061e65-98a2-4ee4-4fad-a50f7b711d0d
  sha: b5a840c7ec4321e78fdc9472e476263fa6614ca1
busybox/busybox-1.27.2.tar.gz:
  size: 692898
  object_id: ed3e7c60-5c94-4359-6c7a-a56eeeffb1de
  sha: 728ef13c40e4a091b22a657a22396b3d985af346
golang/go1.12.5.linux-amd64.tar.gz:
  size: 127938445
  object_id: 0c98b1e5-b557-419e-4c9c-7d41f0fbdf63
  sha: sha256:aea86e3c73495f205929cfebba0d63f1382c8ac59be081b6351681415f4063cf
golang/go1.12.5.windows-amd64.zip:
  size: 141300257
  object_id: 8013d93a-39ac-4522-5eee-5e2f1ad01ec3
  sha: sha256:ccb694279aab39fe0e70629261f13b0307ee40d2d5e1138ed94738023ab04baa
iptables/iptables-1.6.2.tar.bz2:
  size: 639785
  object_id: cafb6233-5827-4b55-4f1d-0da60ca30345
  sha: 6279effbf8f2c7ff53d19ae13308f8a6e6a60dd9
iptables/libmnl-1.0.4.tar.bz2:
  size: 301270
  object_id: f196a106-27aa-48e6-867b-62e33663e578
  sha: 2db40dea612e88c62fd321906be40ab5f8f1685a
iptables/libnftnl-1.0.9.tar.bz2:
  size: 402296
  object_id: 7c9cb0cd-d6e7-461b-4d11-045dcced5eec
  sha: 90b70f52a26f88ab1106671e797faac21265fa6a
libseccomp/libseccomp-2.3.3.tar.gz:
  size: 564546
  object_id: 9f4dbf33-fc5d-421d-5808-efc3a8dc6fd3
  sha: 89b1f35447b1891a3051de979dc92ad9f7258b60
libtool/libtool-2.4.6.tar.gz:
  size: 1806697
  object_id: ddac6c73-578e-4b7d-7ce4-807f46661e85
  sha: 25b6931265230a06f0fc2146df64c04e5ae6ec33
lzo/lzo-2.09.tar.gz:
  size: 594855
  object_id: 39bb6d9a-e168-4137-7751-c8262b743f1d
  sha: e2a60aca818836181e7e6f8c4f2c323aca6ac057
pkg-config/pkg-config-0.29.tar.gz:
  size: 1973875
  object_id: 2c79a436-7142-43d8-663a-2a9340f66418
  sha: f4b19d203b3896a4293af4b62c7f908063c88a5a
tar/tar-1.30.tar.xz:
  size: 2108028
  object_id: dc69bac3-828a-4d65-7479-4ef651208d03
  sha: 0d442c4565f8131745a5dff1cd08f7eaa797f679
tini/tini-v0.18.0.tar.gz:
  size: 32152
  object_id: bfcc2f24-1cf0-432a-67cc-2c19518c839b
  sha: 27b7529ae87ea688e21d0a061b6d9299ff9362f6
util-linux/util-linux-2.28.tar.gz:
  size: 8860808
  object_id: ed756d6a-13d9-475e-6bba-99fc7531b470
  sha: ad8f1a338c23bcf3519b856295fbdb6a820db64c
xfs-progs/xfsprogs-4.20.0.tar.gz:
  size: 1750213
  object_id: 46a0233d-1423-46d8-49ad-b5d0f07a39aa
  sha: 46c23a0e222a3374d9c739b8c44be879712e6e75
zlib/zlib-1.2.11.tar.gz:
  size: 607698
  object_id: 34c42971-0f0e-4704-7530-432d180753af
  sha: e6d119755acdf9104d7ba236b1242696940ed6dd
